name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd ~/ReactChatApp
          git pull origin main
          # Stop and remove containers
          docker compose down
          # Clean up old images
          docker system prune -f
          # Force rebuild without cache
          docker compose build --no-cache
          # Start containers in production mode
          docker compose up -d
          # Verify deployment status
          docker ps
          # Display recent application logs
          docker logs chatapp --tail 50